build:
    environment:
        variables:
            COMPOSER_ROOT_VERSION: '0.10.99'

    tests:
        override:
            -
                command: 'phpdbg -qrr bin/phpunit --coverage-clover=coverage.clover --exclude-group=integration'
                coverage:
                    file: 'coverage.clover'
                    format: 'clover'
