risky: true
preset: symfony

enabled:
    - ordered_use
    - declare_strict_types

disabled:
    - phpdoc_annotation_without_dot # This is still buggy: https://github.com/symfony/symfony/pull/19198
    - phpdoc_inline_tag
    - single_line_throw

finder:
  exclude:
    - 'fixtures'
  not-path:
    - 'src/check.php'
    - 'src/Autoload/Requirements.php'
