name: 'Install a vendor-bin tool'

description: >
    Install a tool installed via bamarni/composer-bin-plugin and runs the associated Makefile command to ensure the
    target is up to date.

inputs:
    vendor-bin-tool:
        required: true
        type: string
    makefile-command:
        required: true
        type: string

runs:
    using: composite
    steps:
        -   name: Install PHP-CS-Fixer
            uses: ramsey/composer-install@1919f6c305aea6ab10e6181a8ddf72317ad77e0e # 2.3.1
            with:
                working-directory: 'vendor-bin/${{ inputs.vendor-bin-tool }}'

        -   name: Ensure PHP-CS-Fixer Makefile target is up to date
            run: make ${{ inputs.makefile-command }}
            shell: sh
