<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;
use Symfony\Bundle\FrameworkBundle\Command\AssetsInstallCommand;
use Symfony\Component\Filesystem\Filesystem;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'console.command.assets_install' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Command/AssetsInstallCommand.php';
include_once $this->targetDirs[3].'/vendor/symfony/filesystem/Filesystem.php';

$this->privates['console.command.assets_install'] = $instance = new AssetsInstallCommand(($this->services['filesystem'] ?? $this->services['filesystem'] = new Filesystem()));

$instance->setName('assets:install');

return $instance;
