<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;
use Symfony\Bundle\FrameworkBundle\Command\RouterMatchCommand;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'console.command.router_match' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Command/RouterMatchCommand.php';

$this->privates['console.command.router_match'] = $instance = new RouterMatchCommand(($this->services['router'] ?? $this->getRouterService()));

$instance->setName('router:match');

return $instance;
