<?php

use Container9sWdsu2\srcDevDebugProjectContainer;
// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9sWdsu2/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container9sWdsu2.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new srcDevDebugProjectContainer(array(
    'container.build_hash' => '9sWdsu2',
    'container.build_id' => '2af0ae2f',
    'container.build_time' => 1540660548,
), __DIR__.\DIRECTORY_SEPARATOR.'Container9sWdsu2');
