<?php

declare(strict_types=1);

/*
 * This file is part of the humbug/php-scoper package.
 *
 * Copyright (c) 2017 Théo FIDRY <theo.fidry@gmail.com>,
 *                    Pádraic Brady <padraic.brady@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Humbug\PhpScoper\Autoload;

use PHPUnit\Framework\TestCase;

class ScoperAutoloadGeneratorTest extends TestCase
{
    public function test_generate_the_autoload()
    {
        $whitelist = [
            'A\Foo',
            'B\Bar',
        ];

        $prefix = 'Humbug';

        $generator = new ScoperAutoloadGenerator($whitelist);

        $expected = <<<'PHP'
<?php

// scoper-autoload.php @generated by PhpScoper

$loader = require_once __DIR__.'/autoload.php'; 

class_exists('Humbug\A\Foo');
class_exists('Humbug\B\Bar');

return $loader;

PHP;

        $actual = $generator->dump($prefix);

        $this->assertSame($expected, $actual);
    }
}
