<?php

declare(strict_types=1);

/*
 * This file is part of the humbug/php-scoper package.
 *
 * Copyright (c) 2017 Théo FIDRY <theo.fidry@gmail.com>,
 *                    Pádraic Brady <padraic.brady@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Humbug\PhpScoper\Autoload;

use Humbug\PhpScoper\PhpParser\NodeVisitor\Collection\UserGlobalFunctionCollection;
use Humbug\PhpScoper\Whitelist;
use PhpParser\Node\Name\FullyQualified;
use PHPUnit\Framework\TestCase;

class ScoperAutoloadGeneratorTest extends TestCase
{
    /**
     * @dataProvider provideWhitelists
     */
    public function test_generate_the_autoload(Whitelist $whitelist, string $expected)
    {
        $prefix = 'Humbug';

        $generator = new ScoperAutoloadGenerator($whitelist);

        $actual = $generator->dump($prefix);

        $this->assertSame($expected, $actual);
    }

    public function provideWhitelists()
    {
        yield [
            Whitelist::create(true, true,'A\Foo', 'B\Bar'),
            <<<'PHP'
<?php

// scoper-autoload.php @generated by PhpScoper

$loader = require_once __DIR__.'/autoload.php';

class_exists('Humbug\A\Foo');
class_exists('Humbug\B\Bar');

return $loader;

PHP
        ];

        yield [
            (function () {
                $whitelist = Whitelist::create(true, true);

                $userGlobalFunctions = new UserGlobalFunctionCollection();
                $userGlobalFunctions->add(
                    new FullyQualified('foo'),
                    new FullyQualified('Humbug\foo')
                );
                $userGlobalFunctions->add(
                    new FullyQualified('bar'),
                    new FullyQualified('Humbug\bar')
                );

                $whitelist->recordUserGlobalFunction($userGlobalFunctions);

                return $whitelist;
            })(),
            <<<'PHP'
<?php

// scoper-autoload.php @generated by PhpScoper

$loader = require_once __DIR__.'/autoload.php'; 

if (!function_exists('foo')) {
    function foo() {
        return \Humbug\foo(func_get_args());
    }
}
if (!function_exists('bar')) {
    function bar() {
        return \Humbug\bar(func_get_args());
    }
}

return $loader;

PHP
        ];

        yield [
            (function () {
                $whitelist = Whitelist::create(true, true,'A\Foo', 'B\Bar');

                $userGlobalFunctions = new UserGlobalFunctionCollection();
                $userGlobalFunctions->add(
                    new FullyQualified('foo'),
                    new FullyQualified('Humbug\foo')
                );
                $userGlobalFunctions->add(
                    new FullyQualified('bar'),
                    new FullyQualified('Humbug\bar')
                );

                $whitelist->recordUserGlobalFunction($userGlobalFunctions);

                return $whitelist;
            })(),
            <<<'PHP'
<?php

// scoper-autoload.php @generated by PhpScoper

$loader = require_once __DIR__.'/autoload.php'; 

class_exists('Humbug\A\Foo');
class_exists('Humbug\B\Bar');
if (!function_exists('foo')) {
    function foo() {
        return \Humbug\foo(func_get_args());
    }
}
if (!function_exists('bar')) {
    function bar() {
        return \Humbug\bar(func_get_args());
    }
}

return $loader;

PHP
        ];
    }
}
