name: Composer Install

on:
    push:
        branches: [ master ]
    pull_request:

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    # see https://getcomposer.org/doc/articles/troubleshooting.md#dependencies-on-the-root-package
    COMPOSER_ROOT_VERSION: 'dev-main'

jobs:
    composer_install:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4

            -
                name: Install dependencies
                run: composer install --ansi
