name: Composer Install

on:
    push:
        branches: [ master ]
    pull_request:

jobs:
    composer_install:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4

            -
                name: Install dependencies
                run: composer install
