name: e2e

on:
    push:
        branches: [ master ]
    pull_request:

jobs:

    e2e:
        runs-on: ubuntu-latest
        name: ${{ matrix.e2e }} - ${{ matrix.php }}
        strategy:
            fail-fast: false
            matrix:
                e2e:
                    - 'e2e_004'
                    - 'e2e_005'
                    - 'e2e_011'
                    - 'e2e_013'
                    - 'e2e_014'
                    - 'e2e_015'
                    - 'e2e_016'
                    - 'e2e_017'
                    - 'e2e_018'
                    - 'e2e_019'
                    - 'e2e_020'
                    - 'e2e_0210'
                    - 'e2e_0211'
                    - 'e2e_022'
                    - 'e2e_023'
                    - 'e2e_024'
                    - 'e2e_025'
                    - 'e2e_026'
                    - 'e2e_028'
                    - 'e2e_029'
                    - 'e2e_030'
                    - 'e2e_031'
                    - 'e2e_032'
                php: [ '7.3', '8.0' ]
                tools: [ 'composer:v2' ]

                include:
                    -   e2e: 'e2e_027'
                        php: '7.3'
                        tools: 'composer:v1'

        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    ini-values: "phar.readonly=0"
                    tools: ${{ matrix.tools }}
                    coverage: pcov

            -   name: Get composer cache directory
                id: composercache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache composer dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composercache.outputs.dir }}
                    key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-cache-

            -   name: Set composer root version
                run: |
                    source .composer-root-version
                    echo "COMPOSER_ROOT_VERSION=${COMPOSER_ROOT_VERSION}" >> $GITHUB_ENV

            -   name: Install dependencies
                run: composer install --no-interaction --no-progress --no-suggest --prefer-dist

            -   name: Run check-composer-root-version
                run: make check-composer-root-version

            -   name: Install tree
                if: matrix.e2e == 'e2e_032'
                run: sudo apt-get install -y tree

            -   name: Run e2e ${{ matrix.e2e }}
                run: make ${{ matrix.e2e }}
