name: Tests

on:
    push:
        branches: [ master ]
    pull_request:
    release:
        types: [ created ]

jobs:
    root-version:
        runs-on: ubuntu-latest
        name: Check COMPOSER_ROOT_VERSION value
        strategy:
            fail-fast: false
            matrix:
                php: [ '8.1' ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    tools: composer
                    coverage: none

            -   name: Check COMPOSER_ROOT_VERSION
                run: make check-composer-root-version

    unit-tests:
        runs-on: ubuntu-latest
        name: Unit tests (PHP ${{ matrix.php }})
        strategy:
            fail-fast: false
            matrix:
                php:
                    - '7.4'
                    - '8.0'
                    - '8.1'
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    tools: composer
                    coverage: none

            # https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#setting-an-environment-variable
            -   name: Configure composer root version
                run: |
                    source .composer-root-version
                    echo "COMPOSER_ROOT_VERSION=${COMPOSER_ROOT_VERSION}" >> $GITHUB_ENV

            -   name: Install Composer dependencies
                uses: ramsey/composer-install@v1
                with:
                    composer-options: '--prefer-dist'

            -   name: Run tests
                run: make tu

    e2e-tests:
        runs-on: ubuntu-latest
        name: 'e2e Test ${{ matrix.e2e }} (PHP: ${{ matrix.php }})'
        strategy:
            fail-fast: false
            matrix:
                e2e:
                    - 'e2e_004'
                    - 'e2e_005'
                    - 'e2e_011'
                    - 'e2e_013'
                    - 'e2e_014'
                    - 'e2e_015'
                    - 'e2e_016'
                    - 'e2e_017'
                    - 'e2e_018'
                    - 'e2e_019'
                    - 'e2e_020'
                    - 'e2e_0210'
                    - 'e2e_0211'
                    - 'e2e_022'
                    - 'e2e_023'
                    - 'e2e_024'
                    - 'e2e_025'
                    - 'e2e_026'
                    - 'e2e_027'
                    - 'e2e_028'
                    - 'e2e_029'
                    - 'e2e_030'
                    - 'e2e_031'
                    - 'e2e_032'
                php:
                    - '7.4'
                    - '8.0'
                    - '8.1'

        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    ini-values: phar.readonly=0
                    tools: composer
                    coverage: pcov

            -   name: Configure composer root version
                run: |
                    source .composer-root-version
                    echo "COMPOSER_ROOT_VERSION=${COMPOSER_ROOT_VERSION}" >> $GITHUB_ENV

            -   name: Install Composer dependencies
                uses: ramsey/composer-install@v1
                with:
                    composer-options: '--prefer-dist'

            -   name: Install tree
                if: matrix.e2e == 'e2e_032'
                run: sudo apt-get install -y tree

            -   name: Run e2e ${{ matrix.e2e }}
                run: make ${{ matrix.e2e }}
