name: GitHub Actions Security Analysis

on:
    push:
        branches: [ main ]
    pull_request: ~
    schedule:
        # Do not make it the first of the month and/or midnight since it is a very busy time
        - cron: "0 10 5 * *"

# See https://stackoverflow.com/a/72408109
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    zizmor:
        runs-on: ubuntu-latest
        name: zizmor
        steps:
            -   name: Checkout
                uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
                with:
                    persist-credentials: false

            -   name: Run zizmor
                uses: zizmorcore/zizmor-action@cc914d7f3750a2d13d75c7f184a1060aa0e9d482 # v0.6.4
                with:
                    # Report the findings as annotations and fail the job instead of
                    # uploading them to the GitHub Security tab.
                    advanced-security: false
